### ISSUE TITLE
Add a link to start a new game in the end game page

### ISSUE THREAD

**Issue by aloisdg** [terraforming-mars/terraforming-mars#5403]
Something like this:

![image](https://user-images.githubusercontent.com/3449303/219961144-7b629887-2c30-4510-94d0-bde7f5335807.png)

What do you think?

Here is an example of the code I used for this demo. If it works for the project, I can open PR.

HTML:
```HTML
<div class="game_end_go_home">
	<div class="whatever_suited_name">
		<a href="/new-game">
			<button class="btn btn-lg btn-rounded">
				<span data-test="icon" class="icon icon-back"></span>
			</button>
			<span>Start a new game</span>
		</a>
		<a href="/">
			<button class="btn btn-lg btn-rounded">
				<span data-test="icon" class="icon icon-back"></span>
			</button>
			<span>Go to main page</span>
		</a>
	</div>
</div>
```

CSS:
```CSS
.whatever_suited_name {
    display: flex;
    flex-direction: column;
}

.game_end_go_home {
    font-size: 30px;
    margin: 40px 0;
    display: flex;
    justify-content: center;

    button {
        margin-right: 10px;
    }
}
```

We could even add a restart button later on.
